name: Java CI

on:
  workflow_dispatch: { }
  push:
    branches:
      - '*'
      - '!gh-pages'
  pull_request:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        javaVersion: [ 11, 14, 17 ]
        javaDist: [ adopt-hotspot, zulu, adopt-openj9 ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:

      - name: Set Git options
        # Check out as-is, commit Unix-style line endings
        run: git config --global core.autocrlf input

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/de/scrum-master
          key: maven-${{ matrix.os }}-java${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ matrix.os }}-java${{ matrix.java }}-
            maven-${{ matrix.os }}-

      - name: Set up JDK
        uses: actions/setup-java@v2.5.0
        with:
          java-version: ${{ matrix.javaVersion }}
          distribution: ${{ matrix.javaDist }}

      - name: Build with Maven
        run: mvn --show-version --errors --batch-mode clean compile exec:java
